### ISSUE TITLE
out folder empty

### ISSUE THREAD

**Issue by giorgiovolpini** [Botmock/botmock-watson-export#12] opened 2019-07-25 09:30 UTC
Hi, I tried to follow step by step instructions, however the script creates the out folder empty. I haven't errors at console.

I create a project, team and a simple flow on BotMock editor and create the .env file with api configuration values for token project team and board, but the json file in the out folder wasn't created.

Can you give some suggestions?

Thanks a lot.

Giorgio

**Comment by nonnontrivial** [comment] 2019-07-25 11:35
Hey @giorgiovolpini ! https://github.com/Botmock/botmock-watson-export/pull/11 just landed, which slightly modifies the output directory path. You can also set the output directory path by giving a value to `OUTPUT_DIR` in `.env`. Can you pull from master and try again?

**Comment by giorgiovolpini** [comment] 2019-07-25 13:02
Hi, now the command npm start shows this errors messages:


(node:29492) ExperimentalWarning: The fs.promises API is experimental
project fetched.
boards fetched.
entities fetched.
intents fetched.
{ Error: Cannot find module './Whatsapp'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:603:15)
    at Function.Module._load (internal/modules/cjs/loader.js:529:25)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at new Provider (<mypath>\Desktop\botmock-watson-export-master\lib\Provider.ts:6:19)
    at getDialogNodesFromMessages (<mypath>\Desktop\botmock-watson-export-master\index.ts:115:20)
    at C:\Users\g.volpini\Desktop\botmock-watson-export-master\index.ts:85:31 code: 'MODULE_NOT_FOUND' }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! botmock-watson-export@1.0.0 start: `ts-node index.ts`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the botmock-watson-export@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     <mypath>\AppData\Roaming\npm-cache\_logs\2019-07-25T12_59_48_794Z-debug.log

**Comment by nonnontrivial** [comment] 2019-07-25 13:20
@giorgiovolpini can you run `node --version`?

**Comment by giorgiovolpini** [comment] 2019-07-25 13:30
Hi, the node version is v11.3.0

**Comment by nonnontrivial** [comment] 2019-07-25 13:33
Hmm. It could be that there is a typo in one or more of the `.env` variables. Can you check that they are
```
BOTMOCK_TOKEN
BOTMOCK_TEAM_ID
BOTMOCK_PROJECT_ID
BOTMOCK_BOARD_ID
```
locally?

**Comment by giorgiovolpini** [comment] 2019-07-25 13:46
I checked, all environemnt variables are configured correctly.

With the previous code version I didn't have this kind of error. Only the out folder empty. :-(

**Comment by nonnontrivial** [comment] 2019-07-25 14:04
@giorgiovolpini can you also try removing `node_modules`, and `package-lock.json` and then running `npm i`?

**Comment by nonnontrivial** [comment] 2019-07-25 14:37
@giorgiovolpini can you try again on latest master?

**Comment by giorgiovolpini** [comment] 2019-07-25 14:49
Downloaded lastest master, npm i, npm install create the .env file with values npm start, but the result is the same.

I don't know....

**Comment by nonnontrivial** [comment] 2019-07-25 17:44
@giorgiovolpini is `/output` being created after running `npm start`?

**Comment by giorgiovolpini** [comment] 2019-07-25 18:10
no, npm start return the same errors

Il gio 25 lug 2019 19:44 Kevin Donahue <notifications@github.com> ha
scritto:

**Comment by nonnontrivial** [comment] 2019-08-21 14:44
Hey @giorgiovolpini , is this still an issue for you? I'm not able to reproduce this.

**Comment by nonnontrivial** [comment] 2020-02-13 18:31
Closing this for now as it is not able to be reproduced.

**Closed by nonnontrivial** 2020-02-13 18:31 UTC
Labels: bug
